### ISSUE TITLE
Needs Documentation

### ISSUE THREAD

**Issue by tonidy** [Modulr/angular-select2#7]
Hi,

I looked into your code but I don't understand your comment. Is there any documentation in English?

Thanks

**Comment by jbeynar** [comment]
+1

**Comment by alfredobarron** [comment]
Hi, I am working to translate comments, I can help you in something?

**Comment by tonidy** [comment]
Hi,

Sorry for late reply. It seem your comment now in English (https://github.com/modulr/mdr-angular-select2/pull/9). Thank you.
